### ISSUE TITLE
newValue is not used in Mixin.SetProperty

### ISSUE THREAD

**Issue by mnaoumov** [sklementiev/mixins#2]
See https://github.com/sklementiev/mixins/blob/develop/Mixins/Mixin.cs#L51

**Comment by sklementiev** [comment]
fixed

**Comment by mnaoumov** [comment]
Why is that closed? Still an issue https://github.com/sklementiev/mixins/blob/develop/Mixins/IMixin.cs#L53

**Comment by mnaoumov** [comment]
Never mind. Somehow I looked into cached old code
